general:
  backendPort: 6662
logger:
database:
  host: smart-validator.net #server host address - default is smart-validator.net
  name: smart_validator_test_5 #actual database name
  user: svt1 #username
  password:  #password
