general:
logger:
database:
  host: localhost:8000 #server host address - default is smart-validator.net
  name: smart_validator_test_5 #actual database name
  user: svt1 #username
  password: XagO7kfuGA1ZMxhP45u7zkna7eMB235zSTfCSzFpOy76OckuubXqlCxGyyC #password
